### ISSUE TITLE
Remove Redundant White Spaces Between Param's Type And Name

### ISSUE THREAD

**Issue by hienkwan** [trgpnt/Java-Class-Annotatable-Constructor-Templater#29]
Here is the example: (as my observation, these extra white spaces mostly added after Generic type Ex: Collection<DummyObject>)
![image](https://github.com/trgpnt/Java-Class-Annotatable-Constructor-Templater/assets/87921972/ec03e11b-adba-4240-93fc-37a9df119637)

**Comment by hienkwan** [comment]
One more clue, in package com.aggregated.inline_tests.intricate_tests.existing_ctor_test.hierarchical_test, there will be increased one more space after each children class.
Ex:
@JsonProperty("listDummy") Collection<DummyObject> listDummy, in BaseClass -> 1 space
@JsonProperty("listDummy") Collection<DummyObject>  listDummy, in Child01 -> 2 spaces
... so on

**Comment by trgpnt** [comment]
Thanks @hienkwan , remote tracking branch is at [29-remove-redundant-white-spaces-between-params-type-and-name](https://github.com/trgpnt/Java-Class-Annotatable-Constructor-Templater/tree/29-remove-redundant-white-spaces-between-params-type-and-name)
