### ISSUE TITLE
New Inserted Constructor Code Should Be Accessed As "Protected" If Its Class Has Any Child

### ISSUE THREAD

**Issue by trgpnt** [trgpnt/Java-Class-Annotatable-Constructor-Templater#5]
# Issue
![image](https://github.com/trgpnt/Java-Class-Annotatable-Constructor-Templater/assets/130839027/84c175c6-1423-46f8-ac15-c64d46dc03e9)

# Expected output :
The access modifier keyword for the **constructor** in the above img should have been **protected** for its children to reference.

**Comment by trgpnt** [comment]
Refer to    https://github.com/trgpnt/Java-Class-Annotatable-Constructor-Templater/blob/b89e8eff02dc058ab98b65323e8f339294685ae0/src/main/java/com/aggregated/BuildAnnotatableCodePhase.java#L848 and https://github.com/trgpnt/Java-Class-Annotatable-Constructor-Templater/blob/b89e8eff02dc058ab98b65323e8f339294685ae0/src/main/java/com/aggregated/BuildAnnotatableCodePhase.java#L851

Maybe a bug..

**Comment by hienkwan** [comment]
This ticket should be able to close now, as it's already been fixed.
![image](https://github.com/trgpnt/Java-Class-Annotatable-Constructor-Templater/assets/87921972/f3355396-e515-44a6-bb05-0a71f33870e0)

**Comment by trgpnt** [comment]
Thanks @hienkwan for the after image !

Closed as far as [test-result](https://github.com/trgpnt/Java-Class-Annotatable-Constructor-Templater/issues/5#issuecomment-1827351352) is concerned
